name: GitHub Secrets
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Secret Setup
        env: 
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
        run:
          echo "Hello"
